import {
  Activity,
  AlertTriangle,
  ArrowUpDown,
  Banknote,
  Bell,
  Boxes,
  Braces,
  Building2,
  Calculator,
  CalendarClock,
  CheckSquare,
  ClipboardList,
  Clock,
  Contact,
  Database,
  DollarSign,
  FileText,
  Filter,
  FilterX,
  GitBranch,
  Globe,
  Handshake,
  KanbanSquare,
  Layers,
  ListTodo,
  Mail,
  MessageCircle,
  MessagesSquare,
  MessageSquare,
  Notebook,
  NotebookText,
  PencilLine,
  Receipt,
  Repeat,
  Rows3,
  Scissors,
  ShoppingBag,
  ShoppingCart,
  Hash,
  Search,
  Send,
  Smartphone,
  Sparkles,
  StickyNote,
  Table2,
  Tags,
  Timer,
  TrendingUp,
  UserCheck,
  UserPlus,
  UserRound,
  Users,
  type LucideIcon,
} from "lucide-react";
import type { BlockKind, WorkflowBlock } from "./types";

export interface BlockDefinition {
  key: string;
  kind: BlockKind;
  /** trigger_type, action_type or logic_type value stored on the block */
  subtype: string;
  label: string;
  description: string;
  icon: LucideIcon;
  color: string;
  section: "TRIGGERS" | "ACTIONS" | "LOGIC";
  usesCredits?: boolean;
  comingSoon?: boolean;
  /** Catalog key of an integration that must be connected before this works. */
  requiresIntegration?: string;
  /**
   * OAuth scopes this block needs on that integration's connection.
   * The block library / config panel diffs this against the
   * connection's granted scopes (integrations.scopes) and prompts a
   * reauthorize flow if anything's missing, instead of letting the
   * block silently fail at run time. See
   * docs/integrations/scopes-and-custom-workflows.md.
   */
  requiredScopes?: string[];
  /**
   * One-line, jargon-free explainer shown under the block title inside the
   * config panel. Written for someone with no technical background.
   */
  configHint?: string;
  /** Extra one-line clarification shown under the description in the config panel. */
  configNote?: string;
  defaultConfig: Record<string, unknown>;
}

export const BLOCK_DEFINITIONS: BlockDefinition[] = [
  {
    key: "webhook",
    configHint: "Starts this workflow whenever your website form (or another tool) sends through a submission.",
    kind: "trigger",
    subtype: "webhook",
    label: "Webhook",
    description: "Receives data from a form, website, or external system",
    icon: Globe,
    color: "var(--accent-green)",
    section: "TRIGGERS",
    defaultConfig: { expected_fields: ["name", "email"] },
  },
  {
    key: "schedule",
    configHint: "Starts this workflow on its own at the time you choose — no one has to click anything.",
    kind: "trigger",
    subtype: "schedule",
    label: "Schedule",
    description: "Runs at a specific time or interval",
    icon: Clock,
    color: "var(--accent-green)",
    section: "TRIGGERS",
    defaultConfig: {
      frequency: "daily",
      time: "07:00",
      timezone: "Africa/Johannesburg",
      days: [],
    },
  },
  {
    key: "email_received",
    configHint: "Starts this workflow when an email is forwarded to your dedicated inbound address.",
    kind: "trigger",
    subtype: "email_received",
    label: "Email received",
    description: "Fires when an email is forwarded to your inbound address",
    icon: Mail,
    color: "var(--accent-green)",
    section: "TRIGGERS",
    defaultConfig: { channel: "resend_inbound", match_all: true },
  },
  {
    key: "slack_message_received",
    configHint: "Starts this workflow whenever someone posts a new message in the Slack channel you pick.",
    kind: "trigger",
    subtype: "slack_message_received",
    label: "New Slack message",
    description: "Fires when a new message is posted in a Slack channel",
    icon: Hash,
    color: "var(--accent-green)",
    section: "TRIGGERS",
    requiresIntegration: "slack",
    defaultConfig: { channel_id: "" },
  },
  {
    key: "slack_unanswered_check",
    configHint: "Starts this workflow when a question in your Slack channel has gone unanswered for too long.",
    kind: "trigger",
    subtype: "slack_unanswered_check",
    label: "Unanswered Slack question",
    description: "Fires when a question in a Slack channel has had no reply",
    icon: Hash,
    color: "var(--accent-green)",
    section: "TRIGGERS",
    requiresIntegration: "slack",
    defaultConfig: { channel_id: "", unanswered_after_hours: 4 },
  },
  {
    key: "slack_daily_digest",
    configHint: "Runs once a day and collects that day's messages from the Slack channel you pick.",
    kind: "trigger",
    subtype: "slack_daily_digest",
    label: "Daily Slack digest",
    description: "Runs once a day over a Slack channel's messages",
    icon: Hash,
    color: "var(--accent-green)",
    section: "TRIGGERS",
    requiresIntegration: "slack",
    defaultConfig: { channel_id: "" },
  },
  {
    key: "hubspot_new_contact",
    configHint: "Starts this workflow whenever a new contact is created in HubSpot.",
    kind: "trigger",
    subtype: "hubspot_event",
    label: "New HubSpot contact",
    description: "Fires when a contact is created in HubSpot",
    icon: Building2,
    color: "var(--accent-green)",
    section: "TRIGGERS",
    requiresIntegration: "hubspot",
    requiredScopes: ["crm.objects.contacts.read"],
    defaultConfig: { subscription_type: "contact.creation", match_all: true },
  },
  {
    key: "hubspot_deal_stage_changed",
    configHint: "Starts this workflow when a deal moves to the pipeline stage you pick.",
    kind: "trigger",
    subtype: "hubspot_event",
    label: "Deal stage changed",
    description: "Fires when a HubSpot deal's stage is updated",
    icon: TrendingUp,
    color: "var(--accent-green)",
    section: "TRIGGERS",
    requiresIntegration: "hubspot",
    requiredScopes: ["crm.objects.deals.read"],
    // match_all: false + a variable/operator/value condition is exactly
    // the evaluate_condition() shape hubspot_webhook.py already uses for
    // filter/if_else — "trigger.dealstage" is the changed deal's new
    // stage on the enriched event payload.
    defaultConfig: {
      subscription_type: "deal.propertyChange",
      match_all: false,
      variable: "trigger.dealstage",
      operator: "equals",
      value: "",
    },
  },
  {
    key: "send_email",
    configHint: "Sends an email automatically. You can drop in details from earlier steps, like the customer's name.",
    kind: "action",
    subtype: "send_email",
    label: "Send email",
    description: "Sends an email",
    icon: Send,
    color: "var(--state-info)",
    section: "ACTIONS",
    defaultConfig: { to: "", subject: "", body: "" },
  },
  {
    key: "wait",
    configHint: "Pauses here for a while before carrying on with the next step.",
    kind: "action",
    subtype: "wait",
    label: "Wait",
    description: "Pauses the workflow for a set time",
    icon: Timer,
    color: "var(--state-warning)",
    section: "ACTIONS",
    defaultConfig: { duration: 1, unit: "hours" },
  },
  {
    key: "save_information",
    configHint: "Stores details from this workflow so you can look them up later.",
    kind: "action",
    subtype: "save_information",
    label: "Save information",
    description: "Creates or updates a record",
    icon: Database,
    color: "var(--state-info)",
    section: "ACTIONS",
    defaultConfig: { collection: "", record_id: "", fields: {} },
  },
  {
    key: "find_information",
    configHint: "Looks up something you saved earlier and brings it into this workflow.",
    configNote:
      "Looks up records your own workflows saved earlier with a 'Save information' step in the same Collection — not your email or any external data.",
    kind: "action",
    subtype: "find_information",
    label: "Find information",
    description: "Looks up a record",
    icon: Search,
    color: "var(--state-info)",
    section: "ACTIONS",
    defaultConfig: { collection: "", filter: "", output_variable: "found_record" },
  },
  {
    key: "summarise_ai",
    configHint: "Turns a long piece of text into a short summary you can reuse in later steps and messages.",
    kind: "action",
    subtype: "summarise_ai",
    label: "Summarise with AI",
    description: "Summarises text into a short overview",
    icon: Sparkles,
    color: "#8B5CF6",
    section: "ACTIONS",
    usesCredits: true,
    defaultConfig: { input: "", max_words: 100, output_variable: "ai_summary" },
  },
  {
    key: "generate_reply_ai",
    configHint: "Writes a reply for you in the tone you pick, based on the message you point it at.",
    kind: "action",
    subtype: "generate_reply_ai",
    label: "Generate reply with AI",
    description: "Writes a reply to a message",
    icon: MessageSquare,
    color: "#8B5CF6",
    section: "ACTIONS",
    usesCredits: true,
    defaultConfig: { context: "", message: "", tone: "Professional", output_variable: "ai_reply" },
  },
  {
    key: "extract_information_ai",
    configHint: "Reads a message and pulls out the specific details you ask for, so later steps can use them.",
    kind: "action",
    subtype: "extract_information_ai",
    label: "Extract information with AI",
    description: "Pulls specific data out of text",
    icon: Scissors,
    color: "#8B5CF6",
    section: "ACTIONS",
    usesCredits: true,
    defaultConfig: { input: "", fields: {}, output_variable: "extracted" },
  },
  {
    key: "send_whatsapp",
    comingSoon: true,
    configHint: "Sends a WhatsApp message.",
    kind: "action",
    subtype: "send_whatsapp",
    label: "Send WhatsApp",
    description: "Sends a WhatsApp message",
    icon: MessageCircle,
    color: "#25D366",
    section: "ACTIONS",
    defaultConfig: { to: "", body: "" },
  },
  {
    key: "send_sms",
    comingSoon: true,
    configHint: "Sends a text message.",
    kind: "action",
    subtype: "send_sms",
    label: "Send SMS",
    description: "Sends an SMS",
    icon: Smartphone,
    color: "#25D366",
    section: "ACTIONS",
    defaultConfig: { to: "", body: "" },
  },
  {
    key: "classify_message_ai",
    configHint: "Reads a message and puts it into one of the categories you list, so later steps can act on the result.",
    kind: "action",
    subtype: "classify_message_ai",
    label: "Classify with AI",
    description: "Sorts a message into categories you define",
    icon: Tags,
    color: "#8B5CF6",
    section: "ACTIONS",
    usesCredits: true,
    defaultConfig: { message: "", categories: [], output_variable: "classification" },
  },
  {
    key: "send_notification",
    configHint: "Puts a notification in your Synkra dashboard, so you see it next time you are in the app.",
    kind: "action",
    subtype: "send_notification",
    label: "Send in-app notification",
    description: "Creates a notification inside the Synkra dashboard",
    icon: Bell,
    color: "var(--state-info)",
    section: "ACTIONS",
    defaultConfig: { title: "", body: "", link: "" },
  },
  {
    key: "hubspot_find_contact",
    configHint: "Looks up an existing HubSpot contact by email — useful before deciding whether to create or update one.",
    kind: "action",
    subtype: "hubspot_find_contact",
    label: "Find HubSpot contact",
    description: "Looks up a HubSpot contact by email",
    icon: Building2,
    color: "#FF7A59",
    section: "ACTIONS",
    requiresIntegration: "hubspot",
    requiredScopes: ["crm.objects.contacts.read"],
    defaultConfig: { email: "", output_variable: "hubspot_contact" },
  },
  {
    key: "hubspot_create_contact",
    configHint: "Creates a new contact in HubSpot with the details you fill in.",
    kind: "action",
    subtype: "hubspot_create_contact",
    label: "Create HubSpot contact",
    description: "Creates a new contact in HubSpot",
    icon: UserPlus,
    color: "#FF7A59",
    section: "ACTIONS",
    requiresIntegration: "hubspot",
    requiredScopes: ["crm.objects.contacts.write"],
    defaultConfig: { properties: { email: "" }, output_variable: "hubspot_contact" },
  },
  {
    key: "hubspot_update_contact",
    configHint: "Updates fields on an existing HubSpot contact.",
    kind: "action",
    subtype: "hubspot_update_contact",
    label: "Update HubSpot contact",
    description: "Updates an existing HubSpot contact's details",
    icon: Building2,
    color: "#FF7A59",
    section: "ACTIONS",
    requiresIntegration: "hubspot",
    requiredScopes: ["crm.objects.contacts.write"],
    defaultConfig: { contact_id: "", properties: {}, output_variable: "hubspot_contact" },
  },
  {
    key: "hubspot_find_deal",
    configHint: "Looks up an existing HubSpot deal by name.",
    kind: "action",
    subtype: "hubspot_find_deal",
    label: "Find HubSpot deal",
    description: "Looks up a HubSpot deal by name",
    icon: TrendingUp,
    color: "#FF7A59",
    section: "ACTIONS",
    requiresIntegration: "hubspot",
    requiredScopes: ["crm.objects.deals.read"],
    defaultConfig: { deal_name: "", output_variable: "hubspot_deal" },
  },
  {
    key: "hubspot_create_deal",
    configHint: "Creates a new deal in HubSpot — set the pipeline and stage you want it to start in.",
    kind: "action",
    subtype: "hubspot_create_deal",
    label: "Create HubSpot deal",
    description: "Creates a new deal in HubSpot",
    icon: TrendingUp,
    color: "#FF7A59",
    section: "ACTIONS",
    requiresIntegration: "hubspot",
    requiredScopes: ["crm.objects.deals.write"],
    defaultConfig: { properties: { dealname: "" }, output_variable: "hubspot_deal" },
  },
  {
    key: "hubspot_update_deal",
    configHint: "Updates fields on an existing HubSpot deal — e.g. moving it to a new stage.",
    kind: "action",
    subtype: "hubspot_update_deal",
    label: "Update HubSpot deal",
    description: "Updates an existing HubSpot deal's details",
    icon: TrendingUp,
    color: "#FF7A59",
    section: "ACTIONS",
    requiresIntegration: "hubspot",
    requiredScopes: ["crm.objects.deals.write"],
    defaultConfig: { deal_id: "", properties: {}, output_variable: "hubspot_deal" },
  },
  {
    key: "hubspot_add_note",
    configHint: "Logs a note on a HubSpot contact's timeline.",
    kind: "action",
    subtype: "hubspot_add_note",
    label: "Add HubSpot note",
    description: "Adds a note to a HubSpot contact's timeline",
    icon: FileText,
    color: "#FF7A59",
    section: "ACTIONS",
    requiresIntegration: "hubspot",
    requiredScopes: ["crm.objects.contacts.write"],
    defaultConfig: { contact_id: "", note_body: "" },
  },
  {
    key: "send_slack_message",
    configHint: "Posts a message to a Slack channel — pick the channel and write the message, using variables from earlier in the workflow if you like.",
    kind: "action",
    subtype: "send_slack_message",
    label: "Send Slack message",
    description: "Posts a message to a Slack channel",
    icon: Hash,
    color: "#E01E5A",
    section: "ACTIONS",
    requiresIntegration: "slack",
    requiredScopes: ["chat:write"],
    defaultConfig: { channel_id: "", text: "" },
  },
  {
    key: "zoho_find_contact",
    configHint: "Looks up an existing Zoho Books contact by email — useful before deciding whether to create or update one.",
    kind: "action",
    subtype: "zoho_find_contact",
    label: "Find Zoho contact",
    description: "Looks up a Zoho Books contact by email",
    icon: DollarSign,
    color: "#E42527",
    section: "ACTIONS",
    requiresIntegration: "zoho",
    requiredScopes: ["ZohoBooks.contacts.READ"],
    defaultConfig: { email: "", output_variable: "zoho_contact" },
  },
  {
    key: "zoho_create_contact",
    configHint: "Creates a new customer or vendor contact in Zoho Books.",
    kind: "action",
    subtype: "zoho_create_contact",
    label: "Create Zoho contact",
    description: "Creates a new contact in Zoho Books",
    icon: UserPlus,
    color: "#E42527",
    section: "ACTIONS",
    requiresIntegration: "zoho",
    requiredScopes: ["ZohoBooks.contacts.CREATE"],
    defaultConfig: { fields: { contact_name: "" }, output_variable: "zoho_contact" },
  },
  {
    key: "zoho_update_contact",
    configHint: "Updates fields on an existing Zoho Books contact.",
    kind: "action",
    subtype: "zoho_update_contact",
    label: "Update Zoho contact",
    description: "Updates an existing Zoho Books contact's details",
    icon: DollarSign,
    color: "#E42527",
    section: "ACTIONS",
    requiresIntegration: "zoho",
    requiredScopes: ["ZohoBooks.contacts.UPDATE"],
    defaultConfig: { contact_id: "", fields: {} },
  },
  {
    key: "zoho_find_invoice",
    configHint: "Looks up an existing Zoho Books invoice by invoice number.",
    kind: "action",
    subtype: "zoho_find_invoice",
    label: "Find Zoho invoice",
    description: "Looks up a Zoho Books invoice by number",
    icon: FileText,
    color: "#E42527",
    section: "ACTIONS",
    requiresIntegration: "zoho",
    requiredScopes: ["ZohoBooks.invoices.READ"],
    defaultConfig: { invoice_number: "", output_variable: "zoho_invoice" },
  },
  {
    key: "zoho_create_invoice",
    configHint: "Creates a new invoice in Zoho Books for a customer.",
    kind: "action",
    subtype: "zoho_create_invoice",
    label: "Create Zoho invoice",
    description: "Creates a new invoice in Zoho Books",
    icon: FileText,
    color: "#E42527",
    section: "ACTIONS",
    requiresIntegration: "zoho",
    requiredScopes: ["ZohoBooks.invoices.CREATE"],
    defaultConfig: { fields: { customer_id: "", line_items: [] }, output_variable: "zoho_invoice" },
  },
  {
    key: "zoho_add_invoice_comment",
    configHint: "Adds an internal comment to a Zoho Books invoice's activity log — not visible to the customer.",
    kind: "action",
    subtype: "zoho_add_invoice_comment",
    label: "Add Zoho invoice comment",
    description: "Adds an internal comment to a Zoho Books invoice",
    icon: FileText,
    color: "#E42527",
    section: "ACTIONS",
    requiresIntegration: "zoho",
    requiredScopes: ["ZohoBooks.invoices.UPDATE"],
    defaultConfig: { invoice_id: "", comment: "" },
  },
  // ————————————————————————————————————————————————————————————
  // Shopify
  // ————————————————————————————————————————————————————————————
  {
    key: "shopify_list_products",
    configHint: "Pulls your products and variants so a later step can review titles, descriptions, pricing, and tags.",
    kind: "action",
    subtype: "shopify_list_products",
    label: "Get Shopify products",
    description: "Retrieves products and variants from your Shopify store",
    icon: ShoppingBag,
    color: "var(--accent-green)",
    section: "ACTIONS",
    requiresIntegration: "shopify",
    requiredScopes: ["read_products"],
    defaultConfig: { limit: 100, output_variable: "shopify_products" },
  },
  {
    key: "shopify_list_inventory",
    configHint: "Pulls current stock levels across your locations.",
    kind: "action",
    subtype: "shopify_list_inventory",
    label: "Get Shopify inventory levels",
    description: "Retrieves current inventory levels from Shopify",
    icon: Boxes,
    color: "var(--accent-green)",
    section: "ACTIONS",
    requiresIntegration: "shopify",
    requiredScopes: ["read_inventory"],
    defaultConfig: { limit: 250, output_variable: "shopify_inventory" },
  },
  {
    key: "shopify_list_orders",
    configHint: "Pulls recent orders so a later step can analyse sales activity.",
    kind: "action",
    subtype: "shopify_list_orders",
    label: "Get Shopify orders",
    description: "Retrieves recent orders from Shopify",
    icon: ShoppingCart,
    color: "var(--accent-green)",
    section: "ACTIONS",
    requiresIntegration: "shopify",
    requiredScopes: ["read_orders"],
    defaultConfig: { days_back: 30, status: "any", output_variable: "shopify_orders" },
  },
  {
    key: "shopify_list_customers",
    configHint: "Pulls your customer list so a later step can review purchasing patterns.",
    kind: "action",
    subtype: "shopify_list_customers",
    label: "Get Shopify customers",
    description: "Retrieves customers from Shopify",
    icon: Users,
    color: "var(--accent-green)",
    section: "ACTIONS",
    requiresIntegration: "shopify",
    requiredScopes: ["read_customers"],
    defaultConfig: { limit: 250, output_variable: "shopify_customers" },
  },
  {
    key: "shopify_get_customer_orders",
    configHint: "Pulls one customer's order history — use a customer ID from an earlier step.",
    kind: "action",
    subtype: "shopify_get_customer_orders",
    label: "Get a customer's Shopify orders",
    description: "Retrieves one customer's order history from Shopify",
    icon: ShoppingCart,
    color: "var(--accent-green)",
    section: "ACTIONS",
    requiresIntegration: "shopify",
    requiredScopes: ["read_orders"],
    defaultConfig: { customer_id: "", output_variable: "shopify_customer_orders" },
  },

  // ————————————————————————————————————————————————————————————
  // Typeform
  // ————————————————————————————————————————————————————————————
  {
    key: "typeform_response_received",
    configHint: "Starts this workflow when someone submits the Typeform you pick. Synkra registers the connection with Typeform for you when you publish, so there is nothing to paste.",
    kind: "trigger",
    subtype: "typeform_response_received",
    label: "New Typeform response",
    description: "Fires when a selected Typeform form receives a new response",
    icon: ClipboardList,
    color: "var(--accent-green)",
    section: "TRIGGERS",
    requiresIntegration: "typeform",
    requiredScopes: ["forms:read", "webhooks:write"],
    defaultConfig: { form_id: "" },
  },
  {
    key: "typeform_get_response",
    configHint: "Pulls the complete answers for the response that triggered this workflow.",
    kind: "action",
    subtype: "typeform_get_response",
    label: "Get Typeform response",
    description: "Retrieves the complete answers for one Typeform response",
    icon: FileText,
    color: "var(--accent-green)",
    section: "ACTIONS",
    requiresIntegration: "typeform",
    requiredScopes: ["responses:read"],
    defaultConfig: { form_id: "", response_id: "{{payload.form_response.token}}", output_variable: "typeform_response" },
  },
  {
    key: "typeform_get_responses",
    configHint: "Pulls responses to a form across a date range, so a later step can look for themes across many answers.",
    kind: "action",
    subtype: "typeform_get_responses",
    label: "Get Typeform responses",
    description: "Retrieves multiple Typeform responses within a date range",
    icon: FileText,
    color: "var(--accent-green)",
    section: "ACTIONS",
    requiresIntegration: "typeform",
    requiredScopes: ["responses:read"],
    defaultConfig: { form_id: "", since: "", until: "", output_variable: "typeform_responses" },
  },

  // ————————————————————————————————————————————————————————————
  // Tally
  // ————————————————————————————————————————————————————————————
  {
    key: "tally_submission_received",
    configHint: "Starts this workflow when someone submits the Tally form you pick. You'll paste this workflow's webhook URL into that form's Integrations > Webhooks settings in Tally.",
    kind: "trigger",
    subtype: "tally_submission_received",
    label: "New Tally submission",
    description: "Fires when a selected Tally form receives a new submission",
    icon: ClipboardList,
    color: "var(--accent-green)",
    section: "TRIGGERS",
    requiresIntegration: "tally",
    requiredScopes: ["full_account"],
    defaultConfig: { form_id: "" },
  },
  {
    key: "tally_get_submission",
    configHint: "Pulls the complete answers for the submission that triggered this workflow.",
    kind: "action",
    subtype: "tally_get_submission",
    label: "Get Tally submission",
    description: "Retrieves the complete answers for one Tally submission",
    icon: FileText,
    color: "var(--accent-green)",
    section: "ACTIONS",
    requiresIntegration: "tally",
    requiredScopes: ["full_account"],
    defaultConfig: { form_id: "", submission_id: "{{payload.data.submissionId}}", output_variable: "tally_submission" },
  },
  {
    key: "tally_get_submissions",
    configHint: "Pulls submissions to a form since a given date, so a later step can look for themes across many answers.",
    kind: "action",
    subtype: "tally_get_submissions",
    label: "Get Tally submissions",
    description: "Retrieves multiple Tally submissions since a given date",
    icon: FileText,
    color: "var(--accent-green)",
    section: "ACTIONS",
    requiresIntegration: "tally",
    requiredScopes: ["full_account"],
    defaultConfig: { form_id: "", since: "", output_variable: "tally_submissions" },
  },

  // ————————————————————————————————————————————————————————————
  // Calendly
  // ————————————————————————————————————————————————————————————
  {
    key: "calendly_meeting_completed",
    // No receiver exists in synkra-core yet, so this trigger cannot fire.
    comingSoon: true,
    configHint: "Starts this workflow when a scheduled meeting finishes. You'll paste this workflow's webhook URL into your Calendly organization's webhook subscriptions.",
    kind: "trigger",
    subtype: "calendly_meeting_completed",
    label: "Calendly meeting completed",
    description: "Fires when a scheduled Calendly meeting is marked complete",
    icon: CalendarClock,
    color: "var(--accent-green)",
    section: "TRIGGERS",
    requiresIntegration: "calendly",
    requiredScopes: ["scheduled_events:read"],
    defaultConfig: { event_type_uri: "" },
  },
  {
    key: "calendly_no_show",
    // No receiver exists in synkra-core yet, so this trigger cannot fire.
    comingSoon: true,
    configHint: "Starts this workflow when an invitee is marked as a no-show for a Calendly meeting.",
    kind: "trigger",
    subtype: "calendly_no_show",
    label: "Calendly no-show",
    description: "Fires when a Calendly invitee is marked a no-show",
    icon: CalendarClock,
    color: "var(--accent-green)",
    section: "TRIGGERS",
    requiresIntegration: "calendly",
    requiredScopes: ["invitees:read"],
    defaultConfig: { event_type_uri: "" },
  },
  {
    key: "calendly_list_scheduled_events",
    configHint: "Pulls Calendly meetings in a date range, so a later step can look across many meetings at once.",
    kind: "action",
    subtype: "calendly_list_scheduled_events",
    label: "Get Calendly events",
    description: "Retrieves scheduled Calendly events in a date range",
    icon: CalendarClock,
    color: "var(--accent-green)",
    section: "ACTIONS",
    requiresIntegration: "calendly",
    requiredScopes: ["scheduled_events:read"],
    defaultConfig: { org_uri: "", min_start_time: "", max_start_time: "", status: "", output_variable: "calendly_events" },
  },
  {
    key: "calendly_get_event_invitees",
    configHint: "Pulls who was invited to (and attended) a specific Calendly meeting.",
    kind: "action",
    subtype: "calendly_get_event_invitees",
    label: "Get Calendly invitees",
    description: "Retrieves the invitees for one Calendly meeting",
    icon: UserCheck,
    color: "var(--accent-green)",
    section: "ACTIONS",
    requiresIntegration: "calendly",
    requiredScopes: ["invitees:read"],
    defaultConfig: { event_uuid: "{{payload.payload.uuid}}", output_variable: "calendly_invitees" },
  },
  {
    key: "calendly_get_meeting_recap",
    configHint: "Pulls the meeting recap/notes for a specific Calendly meeting, when one exists.",
    kind: "action",
    subtype: "calendly_get_meeting_recap",
    label: "Get Calendly meeting recap",
    description: "Retrieves the recap or notes for one Calendly meeting, if available",
    icon: NotebookText,
    color: "var(--accent-green)",
    section: "ACTIONS",
    requiresIntegration: "calendly",
    requiredScopes: ["meeting_recaps:read"],
    defaultConfig: { event_uuid: "{{payload.payload.uuid}}", output_variable: "calendly_recap" },
  },

  // ————————————————————————————————————————————————————————————
  // Xero
  // ————————————————————————————————————————————————————————————
  {
    key: "xero_invoice_changed",
    // No receiver exists in synkra-core yet, so this trigger cannot fire.
    comingSoon: true,
    configHint: "Starts this workflow when an invoice is created or updated in Xero. You'll add this workflow's webhook URL as a subscription in your Xero app's webhook settings.",
    kind: "trigger",
    subtype: "xero_invoice_changed",
    label: "Xero invoice created or updated",
    description: "Fires when a Xero invoice is created or updated",
    icon: Receipt,
    color: "var(--accent-green)",
    section: "TRIGGERS",
    requiresIntegration: "xero",
    requiredScopes: ["accounting.invoices.read", "offline_access"],
    defaultConfig: {},
  },
  {
    key: "xero_list_invoices",
    configHint: "Pulls invoices matching a status (e.g. outstanding/authorised), so a later step can analyse them.",
    kind: "action",
    subtype: "xero_list_invoices",
    label: "Get Xero invoices",
    description: "Retrieves invoices from Xero",
    icon: Receipt,
    color: "var(--accent-green)",
    section: "ACTIONS",
    requiresIntegration: "xero",
    requiredScopes: ["accounting.invoices.read", "offline_access"],
    defaultConfig: { statuses: ["AUTHORISED"], output_variable: "xero_invoices" },
  },
  {
    key: "xero_list_payments",
    configHint: "Pulls recent payments recorded in Xero.",
    kind: "action",
    subtype: "xero_list_payments",
    label: "Get Xero payments",
    description: "Retrieves payments from Xero",
    icon: Banknote,
    color: "var(--accent-green)",
    section: "ACTIONS",
    requiresIntegration: "xero",
    requiredScopes: ["accounting.payments.read", "offline_access"],
    defaultConfig: { output_variable: "xero_payments" },
  },
  {
    key: "xero_get_invoice",
    configHint: "Pulls a single invoice's full details — use an invoice ID from the trigger or an earlier step.",
    kind: "action",
    subtype: "xero_get_invoice",
    label: "Get Xero invoice",
    description: "Retrieves one invoice from Xero",
    icon: Receipt,
    color: "var(--accent-green)",
    section: "ACTIONS",
    requiresIntegration: "xero",
    requiredScopes: ["accounting.invoices.read", "offline_access"],
    defaultConfig: { invoice_id: "{{payload.events.0.resourceId}}", output_variable: "xero_invoice" },
  },
  {
    key: "xero_list_contacts",
    configHint: "Pulls your Xero contacts (customers/suppliers).",
    kind: "action",
    subtype: "xero_list_contacts",
    label: "Get Xero contacts",
    description: "Retrieves contacts from Xero",
    icon: Contact,
    color: "var(--accent-green)",
    section: "ACTIONS",
    requiresIntegration: "xero",
    requiredScopes: ["accounting.contacts.read", "offline_access"],
    defaultConfig: { output_variable: "xero_contacts" },
  },

  // ————————————————————————————————————————————————————————————
  // Airtable
  // ————————————————————————————————————————————————————————————
  {
    key: "airtable_record_changed",
    configHint: "Starts this workflow when a record is created or updated in a table you pick. Set up an Airtable Automation with a webhook action pointing at this workflow's URL.",
    kind: "trigger",
    subtype: "airtable_record_changed",
    label: "Airtable record created or updated",
    description: "Fires when a record in a selected Airtable table changes",
    icon: Table2,
    color: "var(--accent-green)",
    section: "TRIGGERS",
    requiresIntegration: "airtable",
    requiredScopes: ["data.records:read"],
    defaultConfig: { base_id: "", table: "" },
  },
  {
    key: "airtable_list_records",
    configHint: "Pulls records from a table (optionally a view or a filter formula), so a later step can review them.",
    kind: "action",
    subtype: "airtable_list_records",
    label: "Get Airtable records",
    description: "Retrieves records from an Airtable table",
    icon: Table2,
    color: "var(--accent-green)",
    section: "ACTIONS",
    requiresIntegration: "airtable",
    requiredScopes: ["data.records:read"],
    defaultConfig: { base_id: "", table: "", view: "", filter_by_formula: "", max_records: 500, output_variable: "airtable_records" },
  },
  {
    key: "airtable_get_base_schema",
    configHint: "Pulls the tables and fields in a base, so the AI step knows what each field means.",
    kind: "action",
    subtype: "airtable_get_base_schema",
    label: "Get Airtable base schema",
    description: "Retrieves a base's tables and field definitions",
    icon: Rows3,
    color: "var(--accent-green)",
    section: "ACTIONS",
    requiresIntegration: "airtable",
    requiredScopes: ["schema.bases:read"],
    defaultConfig: { base_id: "", output_variable: "airtable_schema" },
  },
  {
    key: "airtable_update_record",
    configHint: "Writes fields back onto one Airtable record — for example, the review result from an AI step.",
    kind: "action",
    subtype: "airtable_update_record",
    label: "Update Airtable record",
    description: "Writes field values back onto one Airtable record",
    icon: PencilLine,
    color: "var(--accent-green)",
    section: "ACTIONS",
    requiresIntegration: "airtable",
    requiredScopes: ["data.records:write"],
    defaultConfig: { base_id: "", table: "", record_id: "", fields: {}, output_variable: "airtable_update_result" },
  },

  // ————————————————————————————————————————————————————————————
  // Monday.com
  // ————————————————————————————————————————————————————————————
  {
    key: "monday_item_changed",
    configHint: "Starts this workflow when an item or its update feed changes on a board you pick.",
    kind: "trigger",
    subtype: "monday_item_changed",
    label: "Monday.com item or update changed",
    description: "Fires when an item or update changes on a selected Monday.com board",
    icon: KanbanSquare,
    color: "var(--accent-green)",
    section: "TRIGGERS",
    requiresIntegration: "monday",
    requiredScopes: ["boards:read", "updates:read", "webhooks:write"],
    defaultConfig: { board_id: "" },
  },
  {
    key: "monday_get_board_items",
    configHint: "Pulls a board's items with their statuses, dates, and recent updates.",
    kind: "action",
    subtype: "monday_get_board_items",
    label: "Get Monday.com board items",
    description: "Retrieves items, statuses, and updates from a Monday.com board",
    icon: KanbanSquare,
    color: "var(--accent-green)",
    section: "ACTIONS",
    requiresIntegration: "monday",
    requiredScopes: ["boards:read", "updates:read"],
    defaultConfig: { board_id: "", limit: 100, output_variable: "monday_items" },
  },
  {
    key: "monday_list_users",
    configHint: "Pulls the people on your Monday.com account, so work can be grouped by owner.",
    kind: "action",
    subtype: "monday_list_users",
    label: "Get Monday.com users",
    description: "Retrieves users on the connected Monday.com account",
    icon: Users,
    color: "var(--accent-green)",
    section: "ACTIONS",
    requiresIntegration: "monday",
    requiredScopes: ["users:read"],
    defaultConfig: { output_variable: "monday_users" },
  },

  // ————————————————————————————————————————————————————————————
  // Asana
  // ————————————————————————————————————————————————————————————
  {
    key: "asana_task_stage_changed",
    configHint: "Starts this workflow when a task moves into a section/stage you pick.",
    kind: "trigger",
    subtype: "asana_task_stage_changed",
    label: "Asana task reaches a stage",
    description: "Fires when a task moves into a selected Asana section",
    icon: ListTodo,
    color: "var(--accent-green)",
    section: "TRIGGERS",
    requiresIntegration: "asana",
    requiredScopes: ["tasks:read", "webhooks:write"],
    defaultConfig: { project_gid: "", section_name: "" },
  },
  {
    key: "asana_list_project_tasks",
    configHint: "Pulls a project's tasks with due dates, assignees, and dependencies.",
    kind: "action",
    subtype: "asana_list_project_tasks",
    label: "Get Asana project tasks",
    description: "Retrieves tasks from an Asana project",
    icon: ListTodo,
    color: "var(--accent-green)",
    section: "ACTIONS",
    requiresIntegration: "asana",
    requiredScopes: ["tasks:read"],
    defaultConfig: { project_gid: "", only_incomplete: true, output_variable: "asana_tasks" },
  },
  {
    key: "asana_get_task_stories",
    configHint: "Pulls the comment/activity history for a single task.",
    kind: "action",
    subtype: "asana_get_task_stories",
    label: "Get Asana task comments",
    description: "Retrieves the comment and activity history for one Asana task",
    icon: MessagesSquare,
    color: "var(--accent-green)",
    section: "ACTIONS",
    requiresIntegration: "asana",
    requiredScopes: ["stories:read"],
    defaultConfig: { task_gid: "", output_variable: "asana_stories" },
  },
  {
    key: "asana_list_overdue_tasks",
    configHint: "Pulls tasks past their due date across a workspace (optionally for one assignee).",
    kind: "action",
    subtype: "asana_list_overdue_tasks",
    label: "Get overdue Asana tasks",
    description: "Retrieves overdue, incomplete tasks from an Asana workspace",
    icon: AlertTriangle,
    color: "var(--accent-green)",
    section: "ACTIONS",
    requiresIntegration: "asana",
    requiredScopes: ["tasks:read"],
    defaultConfig: { workspace_gid: "", assignee_gid: "", output_variable: "asana_overdue_tasks" },
  },

  // ————————————————————————————————————————————————————————————
  // Pipedrive
  // ————————————————————————————————————————————————————————————
  {
    key: "pipedrive_deal_changed",
    configHint: "Starts this workflow when a deal you're tracking is updated in Pipedrive.",
    kind: "trigger",
    subtype: "pipedrive_deal_changed",
    label: "Pipedrive deal updated",
    description: "Fires when a Pipedrive deal is updated",
    icon: Handshake,
    color: "var(--accent-green)",
    section: "TRIGGERS",
    requiresIntegration: "pipedrive",
    requiredScopes: ["deals:read"],
    defaultConfig: {},
  },
  {
    key: "pipedrive_get_deal",
    configHint: "Pulls a single deal's full details.",
    kind: "action",
    subtype: "pipedrive_get_deal",
    label: "Get Pipedrive deal",
    description: "Retrieves one deal from Pipedrive",
    icon: Handshake,
    color: "var(--accent-green)",
    section: "ACTIONS",
    requiresIntegration: "pipedrive",
    requiredScopes: ["deals:read"],
    defaultConfig: { deal_id: "{{payload.current.id}}", output_variable: "pipedrive_deal" },
  },
  {
    key: "pipedrive_list_deals",
    configHint: "Pulls deals by status (e.g. open), so a later step can review your pipeline.",
    kind: "action",
    subtype: "pipedrive_list_deals",
    label: "Get Pipedrive deals",
    description: "Retrieves deals from Pipedrive by status",
    icon: Layers,
    color: "var(--accent-green)",
    section: "ACTIONS",
    requiresIntegration: "pipedrive",
    requiredScopes: ["deals:read"],
    defaultConfig: { status: "open", output_variable: "pipedrive_deals" },
  },
  {
    key: "pipedrive_get_person",
    configHint: "Pulls a contact's details from Pipedrive.",
    kind: "action",
    subtype: "pipedrive_get_person",
    label: "Get Pipedrive contact",
    description: "Retrieves one person/contact from Pipedrive",
    icon: UserRound,
    color: "var(--accent-green)",
    section: "ACTIONS",
    requiresIntegration: "pipedrive",
    requiredScopes: ["contacts:read"],
    defaultConfig: { person_id: "", output_variable: "pipedrive_person" },
  },
  {
    key: "pipedrive_list_deal_activities",
    configHint: "Pulls the scheduled and completed activities logged against a deal.",
    kind: "action",
    subtype: "pipedrive_list_deal_activities",
    label: "Get Pipedrive deal activities",
    description: "Retrieves activities logged against one Pipedrive deal",
    icon: Activity,
    color: "var(--accent-green)",
    section: "ACTIONS",
    requiresIntegration: "pipedrive",
    requiredScopes: ["activities:read"],
    defaultConfig: { deal_id: "", output_variable: "pipedrive_activities" },
  },
  {
    key: "pipedrive_list_deal_notes",
    configHint: "Pulls the notes logged against a deal.",
    kind: "action",
    subtype: "pipedrive_list_deal_notes",
    label: "Get Pipedrive deal notes",
    description: "Retrieves notes logged against one Pipedrive deal",
    icon: StickyNote,
    color: "var(--accent-green)",
    section: "ACTIONS",
    requiresIntegration: "pipedrive",
    requiredScopes: ["deals:read"],
    defaultConfig: { deal_id: "", output_variable: "pipedrive_notes" },
  },
  {
    key: "pipedrive_list_recent_changes",
    configHint: "Pulls what's changed recently in Pipedrive, so a later step can spot deals that have gone quiet by comparing against your full deal list. Defaults to the last 7 days if left blank.",
    kind: "action",
    subtype: "pipedrive_list_recent_changes",
    label: "Get recent Pipedrive changes",
    description: "Retrieves recently changed items from Pipedrive (defaults to the last 7 days)",
    icon: Activity,
    color: "var(--accent-green)",
    section: "ACTIONS",
    requiresIntegration: "pipedrive",
    requiredScopes: ["recents:read"],
    defaultConfig: { since_timestamp: "", items: "deal", output_variable: "pipedrive_recent_changes" },
  },
  {
    key: "pipedrive_list_upcoming_activities",
    configHint: "Pulls activities scheduled in the next day (or however many days you choose) that aren't done yet.",
    kind: "action",
    subtype: "pipedrive_list_upcoming_activities",
    label: "Get upcoming Pipedrive activities",
    description: "Retrieves not-yet-completed activities scheduled in the days ahead",
    icon: CalendarClock,
    color: "var(--accent-green)",
    section: "ACTIONS",
    requiresIntegration: "pipedrive",
    requiredScopes: ["activities:read"],
    defaultConfig: { days_ahead: 1, output_variable: "pipedrive_upcoming_activities" },
  },

  // ————————————————————————————————————————————————————————————
  // ClickUp
  // ————————————————————————————————————————————————————————————
  {
    key: "clickup_new_event",
    configHint: "Starts this workflow when a task in the ClickUp list you choose is created, updated, or commented on.",
    kind: "trigger",
    subtype: "clickup_event",
    label: "New ClickUp event",
    description: "Fires on task activity in a ClickUp list",
    icon: CheckSquare,
    color: "var(--accent-green)",
    section: "TRIGGERS",
    requiresIntegration: "clickup",
    // No requiredScopes — ClickUp's OAuth app model doesn't support
    // granular scopes at all (confirmed against ClickUp's own
    // developer docs). See docs/integrations/clickup-notion-integration.md §3.
    configNote:
      "Publishing a workflow that uses this trigger registers a ClickUp webhook on your Workspace automatically — nothing to set up inside ClickUp itself.",
    defaultConfig: { event: "taskCreated", list_id: "", match_all: true },
  },
  {
    key: "clickup_create_task",
    configHint: "Creates a new task in the ClickUp list you choose, with whatever details you fill in.",
    kind: "action",
    subtype: "clickup_create_task",
    label: "Create ClickUp task",
    description: "Creates a task in a ClickUp list",
    icon: CheckSquare,
    color: "var(--accent-green)",
    section: "ACTIONS",
    requiresIntegration: "clickup",
    defaultConfig: { list_id: "", fields: { name: "", description: "" }, output_variable: "clickup_task" },
  },
  {
    key: "clickup_update_task",
    configHint: "Updates an existing ClickUp task — change its status, priority, assignee or any other field.",
    kind: "action",
    subtype: "clickup_update_task",
    label: "Update ClickUp task",
    description: "Updates fields on an existing ClickUp task",
    icon: CheckSquare,
    color: "var(--accent-green)",
    section: "ACTIONS",
    requiresIntegration: "clickup",
    defaultConfig: { task_id: "", fields: {} },
  },
  {
    key: "clickup_find_task",
    configHint: "Looks up a ClickUp task in a list by matching its name — useful for finding a task this workflow (or a teammate) created earlier.",
    kind: "action",
    subtype: "clickup_find_task",
    label: "Find ClickUp task",
    description: "Looks up a ClickUp task by name within a list",
    icon: Search,
    color: "var(--accent-green)",
    section: "ACTIONS",
    requiresIntegration: "clickup",
    defaultConfig: { list_id: "", search_text: "", output_variable: "clickup_task" },
  },
  {
    key: "clickup_add_comment",
    configHint: "Posts a comment on an existing ClickUp task — handy for logging internal context without changing the task itself.",
    kind: "action",
    subtype: "clickup_add_comment",
    label: "Add ClickUp comment",
    description: "Adds a comment to a ClickUp task",
    icon: MessageSquare,
    color: "var(--accent-green)",
    section: "ACTIONS",
    requiresIntegration: "clickup",
    defaultConfig: { task_id: "", comment_text: "" },
  },

  // ————————————————————————————————————————————————————————————
  // Notion
  // ————————————————————————————————————————————————————————————
  {
    key: "notion_new_item",
    configHint: "Starts this workflow when a new row appears in the Notion database you choose.",
    kind: "trigger",
    subtype: "notion_new_item",
    label: "New Notion database item",
    description: "Fires when a new row is added to a Notion database",
    icon: Notebook,
    color: "var(--accent-green)",
    section: "TRIGGERS",
    requiresIntegration: "notion",
    // No requiredScopes — Notion's OAuth integration model isn't scope-
    // granular either; capabilities are fixed once on the integration
    // itself, not requested per-session. See same doc as above.
    configNote:
      "Checked every few minutes rather than instantly — Notion doesn't offer a live push feed for database changes. Only databases you've shared with Synkra inside Notion will appear in the picker.",
    defaultConfig: { database_id: "" },
  },
  {
    key: "notion_create_page",
    configHint: "Adds a new row to the Notion database you choose, filling in the columns you map.",
    kind: "action",
    subtype: "notion_create_page",
    label: "Create Notion page",
    description: "Creates a new row in a Notion database",
    icon: Notebook,
    color: "var(--accent-green)",
    section: "ACTIONS",
    requiresIntegration: "notion",
    defaultConfig: { database_id: "", properties: {}, output_variable: "notion_page" },
  },
  {
    key: "notion_update_page",
    configHint: "Updates the columns on an existing Notion page — for example, moving a status field along.",
    kind: "action",
    subtype: "notion_update_page",
    label: "Update Notion page",
    description: "Updates properties on an existing Notion page",
    icon: Notebook,
    color: "var(--accent-green)",
    section: "ACTIONS",
    requiresIntegration: "notion",
    defaultConfig: { page_id: "", properties: {} },
  },
  {
    key: "notion_query_database",
    configHint: "Reads the current rows from a Notion database — useful for building a summary or a digest of what's in it.",
    kind: "action",
    subtype: "notion_query_database",
    label: "Query Notion database",
    description: "Reads rows from a Notion database",
    icon: Search,
    color: "var(--accent-green)",
    section: "ACTIONS",
    requiresIntegration: "notion",
    defaultConfig: { database_id: "", output_variable: "notion_results" },
  },
  {
    key: "notion_find_page",
    configHint: "Looks up a single row in a Notion database by matching one of its columns — useful for checking whether a record already exists.",
    kind: "action",
    subtype: "notion_find_page",
    label: "Find Notion page",
    description: "Looks up a row in a Notion database by a column value",
    icon: Search,
    color: "var(--accent-green)",
    section: "ACTIONS",
    requiresIntegration: "notion",
    defaultConfig: { database_id: "", property_name: "", value: "", output_variable: "notion_page" },
  },

  // ————————————————————————————————————————————————————————————
  // Shared AI report block (used by every launch-integration
  // Report/Review/Digest template — see
  // services/workflow_engine.py's execute_ai_business_report)
  // ————————————————————————————————————————————————————————————
  {
    key: "ai_business_report",
    configHint: "Turns raw data from an earlier step into a clear, prioritised written report — tell it what to look for and it does the analysis.",
    kind: "action",
    subtype: "ai_business_report",
    label: "AI business report",
    description: "Uses AI to turn data from an earlier step into a prioritised written report",
    icon: Sparkles,
    color: "var(--state-info)",
    section: "ACTIONS",
    usesCredits: true,
    defaultConfig: { input: "", instructions: "", report_title: "Business report", output_variable: "ai_report" },
  },
  {
    key: "custom_api_call",
    configHint: "For anything the ready-made blocks above don't cover — call any endpoint on a connected platform directly. If it needs a permission you haven't granted yet, you'll be asked to authorize it.",
    kind: "action",
    subtype: "custom_api_call",
    label: "Custom action",
    description: "Calls any endpoint on a connected platform — not limited to the blocks above",
    icon: Braces,
    color: "var(--text-muted)",
    section: "ACTIONS",
    // No fixed requiresIntegration/requiredScopes — both are chosen per
    // use in the config panel (which platform, which endpoint), and the
    // panel writes the resulting scope requirement onto the block
    // instance's `required_scopes` (WorkflowBlock, not this static
    // definition) rather than here. See
    // docs/integrations/scopes-and-custom-workflows.md.
    defaultConfig: { integration: "", method: "GET", endpoint: "", body: {}, output_variable: "api_response" },
  },
  {
    key: "if_else",
    configHint: "Check something and remember the result, so later steps and messages can refer to it.",
    kind: "logic",
    subtype: "if_else",
    label: "Make a decision",
    description: "Sends the workflow down one of two paths",
    icon: GitBranch,
    color: "var(--state-warning)",
    section: "LOGIC",
    defaultConfig: {
      variable: "",
      operator: "equals",
      value: "",
      true_label: "Yes",
      false_label: "No",
    },
  },
  {
    key: "filter",
    configHint: "Checks one thing before going further — if it isn't true, the workflow simply stops here.",
    kind: "logic",
    subtype: "filter",
    label: "Only continue if",
    description: "Stops the workflow if the condition is not met",
    icon: Filter,
    color: "var(--state-warning)",
    section: "LOGIC",
    defaultConfig: { variable: "", operator: "equals", value: "" },
  },
  {
    key: "list_fetch",
    configHint: "Pulls a real list from a connected platform — invoices, contacts, channels — so you can filter, sort, total, or loop over it in later steps.",
    configNote: "Only specific platform + list combinations are supported today. Anything else needs a Custom action block instead.",
    kind: "action",
    subtype: "list_fetch",
    label: "Get a list",
    description: "Fetches a list of records from a connected platform",
    icon: Database,
    color: "var(--accent-green)",
    section: "ACTIONS",
    // No fixed requiresIntegration/requiredScopes, same reasoning as
    // custom_api_call — the platform is chosen per use in the config
    // panel, and the panel writes the resulting scope onto the block
    // instance's required_scopes. See
    // docs/integrations/scopes-and-custom-workflows.md.
    defaultConfig: { platform: "", resource: "", output_variable: "" },
  },
  {
    key: "filter_list",
    configHint: "Narrows a list down to just the items matching one condition — the rest of the list is set aside, not deleted, and the workflow keeps going either way.",
    kind: "logic",
    subtype: "filter_list",
    label: "Narrow a list",
    description: "Keeps only the items in a list that match a condition",
    icon: FilterX,
    color: "var(--state-warning)",
    section: "LOGIC",
    defaultConfig: { list_variable: "", output_variable: "", field: "", operator: "equals", value: "" },
  },
  {
    key: "sort_list",
    configHint: "Puts a list in order by a field — biggest first, oldest first, whatever fits — and can keep just the top few.",
    kind: "logic",
    subtype: "sort_list",
    label: "Sort a list",
    description: "Orders a list by a field, optionally keeping only the top results",
    icon: ArrowUpDown,
    color: "var(--state-warning)",
    section: "LOGIC",
    defaultConfig: { list_variable: "", output_variable: "", field: "", direction: "desc", limit: null },
  },
  {
    key: "aggregate_list",
    configHint: "Turns a whole list into one number — a total, a count, or an average — that later steps can use directly.",
    kind: "logic",
    subtype: "aggregate_list",
    label: "Total a list",
    description: "Sums, counts, or averages a field across a list",
    icon: Calculator,
    color: "var(--state-warning)",
    section: "LOGIC",
    defaultConfig: { list_variable: "", output_variable: "", field: "", operation: "sum" },
  },
  {
    key: "for_each",
    configHint: "Repeats a set of steps once for every item in a list — build the steps that should happen per item separately, using \"Manage steps\" below.",
    configNote: "A Wait block isn't supported inside a loop yet.",
    kind: "logic",
    subtype: "for_each",
    label: "Repeat for each item",
    description: "Runs a set of steps once per item in a list",
    icon: Repeat,
    color: "var(--state-warning)",
    section: "LOGIC",
    defaultConfig: {
      list_variable: "",
      item_variable: "item",
      collect_variable: "",
      output_list_variable: "",
      blocks: [],
    },
  },
];

export const OPERATORS: { value: string; label: string }[] = [
  { value: "equals", label: "Equals" },
  { value: "not_equals", label: "Does not equal" },
  { value: "contains", label: "Contains" },
  { value: "not_contains", label: "Does not contain" },
  { value: "greater_than", label: "Is greater than" },
  { value: "less_than", label: "Is less than" },
  { value: "is_empty", label: "Is empty" },
  { value: "is_not_empty", label: "Is not empty" },
];

export function blockSubtype(block: WorkflowBlock): string {
  return block.trigger_type || block.action_type || block.logic_type || "";
}

export function definitionFor(block: WorkflowBlock): BlockDefinition | undefined {
  const subtype = blockSubtype(block);
  return BLOCK_DEFINITIONS.find((d) => d.subtype === subtype && d.kind === block.type);
}

export function kindColor(kind: BlockKind): string {
  if (kind === "trigger") return "var(--accent-green)";
  if (kind === "logic") return "var(--state-warning)";
  return "var(--state-info)";
}

let counter = 0;
export function createBlock(definition: BlockDefinition): WorkflowBlock {
  counter += 1;
  const id = `${definition.kind}_${Date.now().toString(36)}_${counter}`;
  const block: WorkflowBlock = {
    id,
    type: definition.kind,
    label: definition.label,
    description: definition.description,
    config: JSON.parse(JSON.stringify(definition.defaultConfig)),
    next: null,
  };
  if (definition.kind === "trigger") block.trigger_type = definition.subtype;
  if (definition.kind === "action") block.action_type = definition.subtype;
  if (definition.kind === "logic") block.logic_type = definition.subtype;
  return block;
    }



    
