/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AuthMagicRouteImport } from './routes/auth.magic'
import { Route as CheckoutReturnRouteImport } from './routes/checkout_.return'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardActivityRouteImport } from './routes/dashboard.activity'
import { Route as DashboardApprovalsRouteImport } from './routes/dashboard.approvals'
import { Route as DashboardDataRouteImport } from './routes/dashboard.data'
import { Route as DashboardHelpRouteImport } from './routes/dashboard.help'
import { Route as DashboardIntegrationsRouteImport } from './routes/dashboard.integrations'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard.notifications'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as ResetPasswordConfirmRouteImport } from './routes/reset-password_.confirm'
import { Route as ApiPublicPlansRouteImport } from './routes/api/public/plans'
import { Route as DashboardWorkflowsIndexRouteImport } from './routes/dashboard.workflows.index'
import { Route as ResetPasswordConfirmTokenRouteImport } from './routes/reset-password_.confirm.$token'
import { Route as ApiPublicBillingWebhookRouteImport } from './routes/api/public/billing/webhook'
import { Route as ApiPublicExecutionsCompleteRouteImport } from './routes/api/public/executions/complete'
import { Route as ApiPublicExecutionsStartRouteImport } from './routes/api/public/executions/start'
import { Route as ApiPublicNotificationsTestRouteImport } from './routes/api/public/notifications/test'
import { Route as DashboardWorkflowsBuilderWorkflowIdRouteImport } from './routes/dashboard.workflows.builder.$workflowId'
import { Route as DashboardWorkflowsBuilderNewRouteImport } from './routes/dashboard.workflows.builder.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthMagicRoute = AuthMagicRouteImport.update({
  id: '/auth/magic',
  path: '/auth/magic',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout_/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardActivityRoute = DashboardActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardApprovalsRoute = DashboardApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDataRoute = DashboardDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardHelpRoute = DashboardHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardIntegrationsRoute = DashboardIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const ResetPasswordConfirmRoute = ResetPasswordConfirmRouteImport.update({
  id: '/reset-password_/confirm',
  path: '/reset-password/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPlansRoute = ApiPublicPlansRouteImport.update({
  id: '/api/public/plans',
  path: '/api/public/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWorkflowsIndexRoute = DashboardWorkflowsIndexRouteImport.update({
  id: '/workflows/',
  path: '/workflows/',
  getParentRoute: () => DashboardRoute,
} as any)
const ResetPasswordConfirmTokenRoute =
  ResetPasswordConfirmTokenRouteImport.update({
    id: '/$token',
    path: '/$token',
    getParentRoute: () => ResetPasswordConfirmRoute,
  } as any)
const ApiPublicBillingWebhookRoute = ApiPublicBillingWebhookRouteImport.update({
  id: '/api/public/billing/webhook',
  path: '/api/public/billing/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicExecutionsCompleteRoute =
  ApiPublicExecutionsCompleteRouteImport.update({
    id: '/api/public/executions/complete',
    path: '/api/public/executions/complete',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicExecutionsStartRoute =
  ApiPublicExecutionsStartRouteImport.update({
    id: '/api/public/executions/start',
    path: '/api/public/executions/start',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicNotificationsTestRoute =
  ApiPublicNotificationsTestRouteImport.update({
    id: '/api/public/notifications/test',
    path: '/api/public/notifications/test',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardWorkflowsBuilderWorkflowIdRoute =
  DashboardWorkflowsBuilderWorkflowIdRouteImport.update({
    id: '/workflows/builder/$workflowId',
    path: '/workflows/builder/$workflowId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardWorkflowsBuilderNewRoute =
  DashboardWorkflowsBuilderNewRouteImport.update({
    id: '/workflows/builder/new',
    path: '/workflows/builder/new',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/admin': typeof AdminRoute
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/sign-up': typeof SignUpRoute
  '/signup': typeof SignupRoute
  '/auth/magic': typeof AuthMagicRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/dashboard/activity': typeof DashboardActivityRoute
  '/dashboard/approvals': typeof DashboardApprovalsRoute
  '/dashboard/data': typeof DashboardDataRoute
  '/dashboard/help': typeof DashboardHelpRoute
  '/dashboard/integrations': typeof DashboardIntegrationsRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/reset-password/confirm': typeof ResetPasswordConfirmRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/api/public/plans': typeof ApiPublicPlansRoute
  '/reset-password/confirm/$token': typeof ResetPasswordConfirmTokenRoute
  '/dashboard/workflows/': typeof DashboardWorkflowsIndexRoute
  '/api/public/billing/webhook': typeof ApiPublicBillingWebhookRoute
  '/api/public/executions/complete': typeof ApiPublicExecutionsCompleteRoute
  '/api/public/executions/start': typeof ApiPublicExecutionsStartRoute
  '/api/public/notifications/test': typeof ApiPublicNotificationsTestRoute
  '/dashboard/workflows/builder/$workflowId': typeof DashboardWorkflowsBuilderWorkflowIdRoute
  '/dashboard/workflows/builder/new': typeof DashboardWorkflowsBuilderNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/admin': typeof AdminRoute
  '/checkout': typeof CheckoutRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/sign-up': typeof SignUpRoute
  '/signup': typeof SignupRoute
  '/auth/magic': typeof AuthMagicRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/dashboard/activity': typeof DashboardActivityRoute
  '/dashboard/approvals': typeof DashboardApprovalsRoute
  '/dashboard/data': typeof DashboardDataRoute
  '/dashboard/help': typeof DashboardHelpRoute
  '/dashboard/integrations': typeof DashboardIntegrationsRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/reset-password/confirm': typeof ResetPasswordConfirmRouteWithChildren
  '/dashboard': typeof DashboardIndexRoute
  '/api/public/plans': typeof ApiPublicPlansRoute
  '/reset-password/confirm/$token': typeof ResetPasswordConfirmTokenRoute
  '/dashboard/workflows': typeof DashboardWorkflowsIndexRoute
  '/api/public/billing/webhook': typeof ApiPublicBillingWebhookRoute
  '/api/public/executions/complete': typeof ApiPublicExecutionsCompleteRoute
  '/api/public/executions/start': typeof ApiPublicExecutionsStartRoute
  '/api/public/notifications/test': typeof ApiPublicNotificationsTestRoute
  '/dashboard/workflows/builder/$workflowId': typeof DashboardWorkflowsBuilderWorkflowIdRoute
  '/dashboard/workflows/builder/new': typeof DashboardWorkflowsBuilderNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/admin': typeof AdminRoute
  '/checkout': typeof CheckoutRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/sign-up': typeof SignUpRoute
  '/signup': typeof SignupRoute
  '/auth/magic': typeof AuthMagicRoute
  '/checkout_/return': typeof CheckoutReturnRoute
  '/dashboard/activity': typeof DashboardActivityRoute
  '/dashboard/approvals': typeof DashboardApprovalsRoute
  '/dashboard/data': typeof DashboardDataRoute
  '/dashboard/help': typeof DashboardHelpRoute
  '/dashboard/integrations': typeof DashboardIntegrationsRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/reset-password_/confirm': typeof ResetPasswordConfirmRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/api/public/plans': typeof ApiPublicPlansRoute
  '/reset-password_/confirm/$token': typeof ResetPasswordConfirmTokenRoute
  '/dashboard/workflows/': typeof DashboardWorkflowsIndexRoute
  '/api/public/billing/webhook': typeof ApiPublicBillingWebhookRoute
  '/api/public/executions/complete': typeof ApiPublicExecutionsCompleteRoute
  '/api/public/executions/start': typeof ApiPublicExecutionsStartRoute
  '/api/public/notifications/test': typeof ApiPublicNotificationsTestRoute
  '/dashboard/workflows/builder/$workflowId': typeof DashboardWorkflowsBuilderWorkflowIdRoute
  '/dashboard/workflows/builder/new': typeof DashboardWorkflowsBuilderNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/admin'
    | '/checkout'
    | '/dashboard'
    | '/login'
    | '/reset-password'
    | '/setup'
    | '/sign-up'
    | '/signup'
    | '/auth/magic'
    | '/checkout/return'
    | '/dashboard/activity'
    | '/dashboard/approvals'
    | '/dashboard/data'
    | '/dashboard/help'
    | '/dashboard/integrations'
    | '/dashboard/notifications'
    | '/dashboard/settings'
    | '/reset-password/confirm'
    | '/dashboard/'
    | '/api/public/plans'
    | '/reset-password/confirm/$token'
    | '/dashboard/workflows/'
    | '/api/public/billing/webhook'
    | '/api/public/executions/complete'
    | '/api/public/executions/start'
    | '/api/public/notifications/test'
    | '/dashboard/workflows/builder/$workflowId'
    | '/dashboard/workflows/builder/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/admin'
    | '/checkout'
    | '/login'
    | '/reset-password'
    | '/setup'
    | '/sign-up'
    | '/signup'
    | '/auth/magic'
    | '/checkout/return'
    | '/dashboard/activity'
    | '/dashboard/approvals'
    | '/dashboard/data'
    | '/dashboard/help'
    | '/dashboard/integrations'
    | '/dashboard/notifications'
    | '/dashboard/settings'
    | '/reset-password/confirm'
    | '/dashboard'
    | '/api/public/plans'
    | '/reset-password/confirm/$token'
    | '/dashboard/workflows'
    | '/api/public/billing/webhook'
    | '/api/public/executions/complete'
    | '/api/public/executions/start'
    | '/api/public/notifications/test'
    | '/dashboard/workflows/builder/$workflowId'
    | '/dashboard/workflows/builder/new'
  id:
    | '__root__'
    | '/'
    | '/accept-invite'
    | '/admin'
    | '/checkout'
    | '/dashboard'
    | '/login'
    | '/reset-password'
    | '/setup'
    | '/sign-up'
    | '/signup'
    | '/auth/magic'
    | '/checkout_/return'
    | '/dashboard/activity'
    | '/dashboard/approvals'
    | '/dashboard/data'
    | '/dashboard/help'
    | '/dashboard/integrations'
    | '/dashboard/notifications'
    | '/dashboard/settings'
    | '/reset-password_/confirm'
    | '/dashboard/'
    | '/api/public/plans'
    | '/reset-password_/confirm/$token'
    | '/dashboard/workflows/'
    | '/api/public/billing/webhook'
    | '/api/public/executions/complete'
    | '/api/public/executions/start'
    | '/api/public/notifications/test'
    | '/dashboard/workflows/builder/$workflowId'
    | '/dashboard/workflows/builder/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcceptInviteRoute: typeof AcceptInviteRoute
  AdminRoute: typeof AdminRoute
  CheckoutRoute: typeof CheckoutRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SetupRoute: typeof SetupRoute
  SignUpRoute: typeof SignUpRoute
  SignupRoute: typeof SignupRoute
  AuthMagicRoute: typeof AuthMagicRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  ResetPasswordConfirmRoute: typeof ResetPasswordConfirmRouteWithChildren
  ApiPublicPlansRoute: typeof ApiPublicPlansRoute
  ApiPublicBillingWebhookRoute: typeof ApiPublicBillingWebhookRoute
  ApiPublicExecutionsCompleteRoute: typeof ApiPublicExecutionsCompleteRoute
  ApiPublicExecutionsStartRoute: typeof ApiPublicExecutionsStartRoute
  ApiPublicNotificationsTestRoute: typeof ApiPublicNotificationsTestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/magic': {
      id: '/auth/magic'
      path: '/auth/magic'
      fullPath: '/auth/magic'
      preLoaderRoute: typeof AuthMagicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout_/return': {
      id: '/checkout_/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/activity': {
      id: '/dashboard/activity'
      path: '/activity'
      fullPath: '/dashboard/activity'
      preLoaderRoute: typeof DashboardActivityRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/approvals': {
      id: '/dashboard/approvals'
      path: '/approvals'
      fullPath: '/dashboard/approvals'
      preLoaderRoute: typeof DashboardApprovalsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/data': {
      id: '/dashboard/data'
      path: '/data'
      fullPath: '/dashboard/data'
      preLoaderRoute: typeof DashboardDataRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/help': {
      id: '/dashboard/help'
      path: '/help'
      fullPath: '/dashboard/help'
      preLoaderRoute: typeof DashboardHelpRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/integrations': {
      id: '/dashboard/integrations'
      path: '/integrations'
      fullPath: '/dashboard/integrations'
      preLoaderRoute: typeof DashboardIntegrationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/reset-password_/confirm': {
      id: '/reset-password_/confirm'
      path: '/reset-password/confirm'
      fullPath: '/reset-password/confirm'
      preLoaderRoute: typeof ResetPasswordConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/plans': {
      id: '/api/public/plans'
      path: '/api/public/plans'
      fullPath: '/api/public/plans'
      preLoaderRoute: typeof ApiPublicPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/workflows/': {
      id: '/dashboard/workflows/'
      path: '/workflows'
      fullPath: '/dashboard/workflows/'
      preLoaderRoute: typeof DashboardWorkflowsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/reset-password_/confirm/$token': {
      id: '/reset-password_/confirm/$token'
      path: '/$token'
      fullPath: '/reset-password/confirm/$token'
      preLoaderRoute: typeof ResetPasswordConfirmTokenRouteImport
      parentRoute: typeof ResetPasswordConfirmRoute
    }
    '/api/public/billing/webhook': {
      id: '/api/public/billing/webhook'
      path: '/api/public/billing/webhook'
      fullPath: '/api/public/billing/webhook'
      preLoaderRoute: typeof ApiPublicBillingWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/executions/complete': {
      id: '/api/public/executions/complete'
      path: '/api/public/executions/complete'
      fullPath: '/api/public/executions/complete'
      preLoaderRoute: typeof ApiPublicExecutionsCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/executions/start': {
      id: '/api/public/executions/start'
      path: '/api/public/executions/start'
      fullPath: '/api/public/executions/start'
      preLoaderRoute: typeof ApiPublicExecutionsStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/notifications/test': {
      id: '/api/public/notifications/test'
      path: '/api/public/notifications/test'
      fullPath: '/api/public/notifications/test'
      preLoaderRoute: typeof ApiPublicNotificationsTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/workflows/builder/$workflowId': {
      id: '/dashboard/workflows/builder/$workflowId'
      path: '/workflows/builder/$workflowId'
      fullPath: '/dashboard/workflows/builder/$workflowId'
      preLoaderRoute: typeof DashboardWorkflowsBuilderWorkflowIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/workflows/builder/new': {
      id: '/dashboard/workflows/builder/new'
      path: '/workflows/builder/new'
      fullPath: '/dashboard/workflows/builder/new'
      preLoaderRoute: typeof DashboardWorkflowsBuilderNewRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardActivityRoute: typeof DashboardActivityRoute
  DashboardApprovalsRoute: typeof DashboardApprovalsRoute
  DashboardDataRoute: typeof DashboardDataRoute
  DashboardHelpRoute: typeof DashboardHelpRoute
  DashboardIntegrationsRoute: typeof DashboardIntegrationsRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardWorkflowsIndexRoute: typeof DashboardWorkflowsIndexRoute
  DashboardWorkflowsBuilderWorkflowIdRoute: typeof DashboardWorkflowsBuilderWorkflowIdRoute
  DashboardWorkflowsBuilderNewRoute: typeof DashboardWorkflowsBuilderNewRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardActivityRoute: DashboardActivityRoute,
  DashboardApprovalsRoute: DashboardApprovalsRoute,
  DashboardDataRoute: DashboardDataRoute,
  DashboardHelpRoute: DashboardHelpRoute,
  DashboardIntegrationsRoute: DashboardIntegrationsRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardWorkflowsIndexRoute: DashboardWorkflowsIndexRoute,
  DashboardWorkflowsBuilderWorkflowIdRoute:
    DashboardWorkflowsBuilderWorkflowIdRoute,
  DashboardWorkflowsBuilderNewRoute: DashboardWorkflowsBuilderNewRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface ResetPasswordConfirmRouteChildren {
  ResetPasswordConfirmTokenRoute: typeof ResetPasswordConfirmTokenRoute
}

const ResetPasswordConfirmRouteChildren: ResetPasswordConfirmRouteChildren = {
  ResetPasswordConfirmTokenRoute: ResetPasswordConfirmTokenRoute,
}

const ResetPasswordConfirmRouteWithChildren =
  ResetPasswordConfirmRoute._addFileChildren(ResetPasswordConfirmRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcceptInviteRoute: AcceptInviteRoute,
  AdminRoute: AdminRoute,
  CheckoutRoute: CheckoutRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SetupRoute: SetupRoute,
  SignUpRoute: SignUpRoute,
  SignupRoute: SignupRoute,
  AuthMagicRoute: AuthMagicRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  ResetPasswordConfirmRoute: ResetPasswordConfirmRouteWithChildren,
  ApiPublicPlansRoute: ApiPublicPlansRoute,
  ApiPublicBillingWebhookRoute: ApiPublicBillingWebhookRoute,
  ApiPublicExecutionsCompleteRoute: ApiPublicExecutionsCompleteRoute,
  ApiPublicExecutionsStartRoute: ApiPublicExecutionsStartRoute,
  ApiPublicNotificationsTestRoute: ApiPublicNotificationsTestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
